interface card {
    id: number;
    name: string;
    showTOAllProduct?: boolean;
    image: string;
    category: string;
}

export const cardData: card[] = [
    {
        id: 1,
        name: "two shelves chaat display counter",
        showTOAllProduct: true,
        image: "/images/products/stainless-steel-two-shelves-chaat-display-counter-2222741116-fq1s7gna.avif",
        category: "display counter",
    },
    {
        id: 2,
        name: "Cash Counter 1",
        showTOAllProduct: true,
        image: "/images/products/Cash_Counter_1.webp",
        category: "Counter Range",
    },
    {
        id: 3,
        name: "Cash Counter 2",
        showTOAllProduct: false,
        image: "/images/products/Cash_Counter_2.webp",
        category: "Counter Range",
    },
    {
        id: 4,
        name: "casting Biryani Burner",
        showTOAllProduct: false,
        image: "/images/products/casting_Biryani_Burner.webp",
        category: "burner",
    },
    {
        id: 5,
        name: "Catering Double Burner Table Top",
        showTOAllProduct: true,
        image: "/images/products/Catering_Double_Burnner_Table_Top.webp",
        category: "burner",
    },
    {
        id: 6,
        name: "Customize Counter With Roof",
        showTOAllProduct: false,
        image: "/images/products/Customize_Counter_With_Roof.webp",
        category: "Counter Range",
    },
    {
        id: 7,
        name: "Dhokla Cooker",
        showTOAllProduct: false,
        image: "/images/products/Dhokla_Cooker.webp",
        category: "steamer range",
    },
    {
        id: 8,
        name: "Dhokla Steamer 6 Tray",
        showTOAllProduct: true,
        image: "/images/products/Dhokla_Steamer_6_Tray.webp",
        category: "steamer range",
    },
    {
        id: 9,
        name: "Dhokla Steamer 8 Tray",
        showTOAllProduct: true,
        image: "/images/products/Dhokla_Steamer_8_Tray.webp",
        category: "steamer range",
    },
    {
        id: 10,
        name: "Dish Landing",
        showTOAllProduct: false,
        image: "/images/products/Dish_Landing.webp",
        category: "sink unit",
    },
    {
        id: 11,
        name: "Dish Landing With Table",
        showTOAllProduct: false,
        image: "/images/products/Dish_Landing_With_Table.webp",
        category: "sink unit",
    },
    {
        id: 12,
        name: "Dosa Bhatti",
        showTOAllProduct: true,
        image: "/images/products/Dosa_Bhatti.webp",
        category: "roti bhatti",
    },
    {
        id: 13,
        name: "Dosa Bhatti Table Top",
        showTOAllProduct: false,
        image: "/images/products/Dosa_Bhatti_Table_Top.webp",
        category: "roti bhatti",
    },
    {
        id: 14,
        name: "Double burner",
        showTOAllProduct: false,
        image: "/images/products/Double_burner.webp",
        category: "burner",
    },
    {
        id: 15,
        name: "Double Deck Stone Oven",
        showTOAllProduct: true,
        image: "/images/products/Double_Deck_Stone_Oven.webp",
        category: "oven",
    },
    {
        id: 16,
        name: "Double Fryer 6 Litre",
        showTOAllProduct: true,
        image: "/images/products/Double_Fryer_6_Litre.webp",
        category: "fryer range",
    },
    {
        id: 17,
        name: "Double Hydraulic Griller",
        showTOAllProduct: true,
        image: "/images/products/Double_Hydraulic_Griller.webp",
        category: "griller range",
    },
    {
        id: 18,
        name: "Double Sink",
        showTOAllProduct: false,
        image: "/images/products/Double_Sink.webp",
        category: "sink unit",
    },
    {
        id: 19,
        name: "Eight Pot Bain Maire",
        showTOAllProduct: false,
        image: "/images/products/Eight_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 20,
        name: "Four Burner",
        showTOAllProduct: true,
        image: "/images/products/Four_Burner.webp",
        category: "burner",
    },
    {
        id: 21,
        name: "Four Pot Bain Maire",
        showTOAllProduct: false,
        image: "/images/products/Four_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 22,
        name: "Gn Pan Bain Marie 1",
        showTOAllProduct: false,
        image: "/images/products/Gn_Pan_Bain_Marie_1.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 23,
        name: "Gn Pan Bain Marie 2",
        showTOAllProduct: false,
        image: "/images/products/Gn_Pan_Bain_Marie_2.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 24,
        name: "Gn Pan Bain Marie 3",
        showTOAllProduct: false,
        image: "/images/products/Gn_Pan_Bain_Marie_3.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 25,
        name: "Gn Pan Bain Marie 4",
        showTOAllProduct: false,
        image: "/images/products/Gn_Pan_Bain_Marie_4.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 26,
        name: "Gn Pan Bain Marie 5",
        showTOAllProduct: false,
        image: "/images/products/Gn_Pan_Bain_Marie_5.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 27,
        name: "Idli Cooker",
        showTOAllProduct: false,
        image: "/images/products/Idli_Cooker.webp",
        category: "steamer range",
    },
    {
        id: 28,
        name: "Idli Steamer 6 Tray",
        showTOAllProduct: false,
        image: "/images/products/Idli_Steamer_6_Tray.webp",
        category: "steamer range",
    },
    {
        id: 29,
        name: "Idli Steamer 8 Tray",
        showTOAllProduct: false,
        image: "/images/products/Idli_Steamer_8_Tray.webp",
        category: "steamer range",
    },
    {
        id: 30,
        name: "Indian Pizza Oven",
        showTOAllProduct: false,
        image: "/images/products/Indian_Pizza_Oven.webp",
        category: "oven",
    },
    {
        id: 31,
        name: "Indian Sandwich Griller",
        showTOAllProduct: false,
        image: "/images/products/Indian_Sandwich_Griller.webp",
        category: "griller range",
    },
    {
        id: 32,
        name: "Khaman Steamer 6 Tray",
        showTOAllProduct: false,
        image: "/images/products/Khaman_Steamer_6_Tray.webp",
        category: "steamer range",
    },
    {
        id: 33,
        name: "Khaman Steamer 8 Tray",
        showTOAllProduct: false,
        image: "/images/products/Khaman_Steamer_8_Tray.webp",
        category: "steamer range",
    },
    {
        id: 34,
        name: "Masala Trolley",
        showTOAllProduct: false,
        image: "/images/products/Masala_Trolley.webp",
        category: "trolley",
    },
    {
        id: 35,
        name: "Ms Chinese Burner",
        showTOAllProduct: true,
        image: "/images/products/Ms_Chinese_Burner.webp",
        category: "burner",
    },
    {
        id: 36,
        name: "Ms Rack 4 Shelves",
        showTOAllProduct: true,
        image: "/images/products/Ms_Rack_4_Shelves.webp",
        category: "StorageRack",
    },
    {
        id: 37,
        name: "One Pot Bain Maire",
        showTOAllProduct: false,
        image: "/images/products/One_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 38,
        name: "Pickup Table 1 Ohs And 2 Us",
        showTOAllProduct: true,
        image: "/images/products/Pickup_Table_1_Ohs_And_2_Us.webp",
        category: "work table",
    },
    {
        id: 39,
        name: "Pickup Table 2 Ohs And 1 Us",
        showTOAllProduct: false,
        image: "/images/products/Pickup_Table_2_Ohs_And_1_Us.webp",
        category: "work table",
    },
    {
        id: 40,
        name: "Pickup Table 2 Ohs And 2 Us",
        showTOAllProduct: false,
        image: "/images/products/Pickup_Table_2_Ohs_And_2_Us.webp",
        category: "work table",
    },
    {
        id: 41,
        name: "Pot Burne",
        showTOAllProduct: false,
        image: "/images/products/Pot_Burne.webp",
        category: "burner",
    },
    {
        id: 42,
        name: "Pot Sink",
        showTOAllProduct: false,
        image: "/images/products/Pot_Sink.webp",
        category: "sink unit",
    },
    {
        id: 43,
        name: "Roti Bhatti Bullet",
        showTOAllProduct: false,
        image: "/images/products/Roti_Bhatti_Bullet.webp",
        category: "roti bhatti",
    },
    {
        id: 44,
        name: "Roti Bhatti Bullet Table Top",
        showTOAllProduct: true,
        image: "/images/products/Roti_Bhatti_Bullet_Table_Top.webp",
        category: "roti bhatti",
    },
    {
        id: 45,
        name: "Roti Bhatti Casting",
        showTOAllProduct: false,
        image: "/images/products/Roti_Bhatti_Casting.webp",
        category: "roti bhatti",
    },
    {
        id: 46,
        name: "Roti Bhatti Casting Table Top",
        showTOAllProduct: false,
        image: "/images/products/Roti_Bhatti_Casting_Table_Top.webp",
        category: "roti bhatti",
    },
    {
        id: 47,
        name: "Salamander",
        showTOAllProduct: false,
        image: "/images/products/Salamander.webp",
        category: "oven",
    },
    {
        id: 48,
        name: "Service Table 1 Under Shelf",
        showTOAllProduct: false,
        image: "/images/products/Service_Table_1_Under_Shelf.webp",
        category: "work table",
    },
    {
        id: 49,
        name: "Service Table 2 Under Shelf",
        showTOAllProduct: false,
        image: "/images/products/Service_Table_2_Under_Shelf.webp",
        category: "work table",
    },
    {
        id: 50,
        name: "Service Table 2 Us With Backsplash",
        showTOAllProduct: false,
        image: "/images/products/Service_Table_2_Us_With_Backsplash.webp",
        category: "work table",
    },
    {
        id: 51,
        name: "Service Table No Under Shelf",
        showTOAllProduct: false,
        image: "/images/products/Service_Table_No_Under_Shelf.webp",
        category: "work table",
    },
    {
        id: 52,
        name: "Single Burner",
        showTOAllProduct: false,
        image: "/images/products/Single_Burner.webp",
        category: "burner",
    },
    {
        id: 53,
        name: "Single Burner with table",
        showTOAllProduct: false,
        image: "/images/products/Single_Burner_with_table.webp",
        category: "burner",
    },
    {
        id: 54,
        name: "Single deck Double tray Oven",
        showTOAllProduct: false,
        image: "/images/products/Single_deck_Double_tray_Oven.webp",
        category: "oven",
    },
    {
        id: 55,
        name: "stainless steel four wheeler",
        showTOAllProduct: true,
        image: "/images/products/stainless-steel-four-wheeler-kitchen-trolley-silver-2222742408-sg4wz8l8.avif",
        category: "trolley",

    },
    {
        id: 56,
        name: "single Deck Stone Oven",
        showTOAllProduct: false,
        image: "/images/products/single_Deck_Stone_Oven.webp",
        category: "oven",
    },
    {
        id: 57,
        name: "Single Fryer 4 Litre",
        showTOAllProduct: false,
        image: "/images/products/Single_Fryer_4_Litre.webp",
        category: "fryer range",
    },
    {
        id: 58,
        name: "Single Fryer 6 Litre",
        showTOAllProduct: false,
        image: "/images/products/Single_Fryer_6_Litre.webp",
        category: "fryer range",
    },
    {
        id: 59,
        name: "Single Hydraulic Griller",
        showTOAllProduct: false,
        image: "/images/products/Single_Hydraulic_Griller.webp",
        category: "griller range",
    },
    {
        id: 60,
        name: "Single Sink",
        showTOAllProduct: false,
        image: "/images/products/Single_Sink.webp",
        category: "sink unit",
    },
    {
        id: 61,
        name: "Single Sink With Table",
        showTOAllProduct: true,
        image: "/images/products/Single_Sink_With_Table.webp",
        category: "sink unit",
    },
    {
        id: 62,
        name: "Six Pot 1 21gn Pan Bain Marie",
        showTOAllProduct: true,
        image: "/images/products/Six_Pot_1_21gn_Pan_Bain_Marie.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 63,
        name: "Six Pot Bain Maire",
        showTOAllProduct: false,
        image: "/images/products/Six_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 64,
        name: "Ss 4 Pot Dish Cooling Rack",
        showTOAllProduct: false,
        image: "/images/products/Ss_4_Pot_Dish_Cooling_Rack.webp",
        category: "StorageRack",
    },
    {
        id: 65,
        name: "Ss Catering Burner",
        showTOAllProduct: false,
        image: "/images/products/Ss_Catering_Burner.webp",
        category: "burner",
    },
    {
        id: 66,
        name: "Ss Counter",
        showTOAllProduct: false,
        image: "/images/products/Ss_Counter.webp",
        category: "Counter Range",
    },
    {
        id: 67,
        name: "Ss Counter With Over 3 Side Covering",
        showTOAllProduct: false,
        image: "/images/products/Ss_Counter_With_Over_3_Side_Covering.webp",
        category: "Counter Range",
    },
    {
        id: 68,
        name: "Ss Pickup Counter",
        showTOAllProduct: true,
        image: "/images/products/Ss_Pickup_Counter.webp",
        category: "Counter Range",
    },
    {
        id: 69,
        name: "Ss Storage Rack",
        showTOAllProduct: false,
        image: "/images/products/Ss_Storage_Rack.webp",
        category: "StorageRack",
    },
    {
        id: 70,
        name: "Stone Top Service Table",
        showTOAllProduct: false,
        image: "/images/products/Stone_Top_Service_Table.webp",
        category: "work table",
    },
    {
        id: 71,
        name: "Three Burner",
        showTOAllProduct: false,
        image: "/images/products/Three_Burner.webp",
        category: "burner",
    },
    {
        id: 72,
        name: "Three Sink",
        showTOAllProduct: true,
        image: "/images/products/Three_Sink.webp",
        category: "sink unit",
    },
    {
        id: 73,
        name: "Three Tier Trolley",
        showTOAllProduct: false,
        image: "/images/products/Three_Tier_Trolley.webp",
        category: "trolley",
    },
    {
        id: 74,
        name: "Two Burner low Height",
        showTOAllProduct: false,
        image: "/images/products/Two_Burner_low_Height.webp",
        category: "burner",
    },
    {
        id: 75,
        name: "Two Pot Bain Maire",
        showTOAllProduct: false,
        image: "/images/products/Two_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 76,
        name: "commercial food counter for restaurant",
        showTOAllProduct: true,
        image: "/images/products/stainless-steel-commercial-food-counter-for-restaurant-2222741232-rkhm2equ.avif",
        category: "display counter",
    },
    {
        id: 77,
        name: "food display counter 7x5 feet",
        showTOAllProduct: false,
        image: "/images/products/stainless-steel-food-display-counter-7x5-feet-silver-2222741625-l7du6a49.avif",
        category: "display counter",
    },
    {
        id: 78,
        name: "four door vertical refrigerator",
        showTOAllProduct: true,
        image: "/images/products/stainless-steel-four-door-vertical-refrigerator-for-kitchen-silver-2222741164-7ex45usd.avif",
        category: "refrigerator",
    },
    {
        id: 79,
        name: "rectangular commercial kitchen trolley",
        showTOAllProduct: false,
        image: "/images/products/stainless-steel-rectangular-commercial-kitchen-trolley-silver-2222742676-nvvvdk51.avif",
        category: "trolley",
    },
    {
        id: 80,
        name: "rectangular deep fryer machine",
        showTOAllProduct: false,
        image: "/images/products/stainless-steel-rectangular-deep-fryer-machine-silver-2222741740-12axdo6c.avif",
        category: "Bain Marie",
    },
    {
        id: 81,
        name: "1 2 2gn Pan Table Top Bain Marie",
        showTOAllProduct: false,
        image: "/images/products/1_2_2gn_Pan_Table_Top_Bain_Marie.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 82,
        name: "shawarma machine with cabinet",
        showTOAllProduct: false,
        image: "/images/products/shawarma-machine-with-cabinet.webp",
        category: "shawarma machine",
    },
    {
        id: 83,
        name: "shawarma machine with counter",
        showTOAllProduct: true,
        image: "/images/products/shawarma-machine-with-counter.webp",
        category: "shawarma machine",
    },
    {
        id: 84,
        name: "shawarma machine with without stand",
        showTOAllProduct: false,
        image: "/images/products/shawarma-machine-without-stand.webp",
        category: "shawarma machine",
    },
    {
        id: 85,
        name: "ss vertical 6 door fridge",
        showTOAllProduct: false,
        image: "/images/products/ss-vertical-6-door-fridge.webp",
        category: "refrigerator",
    },
    {
        id: 86,
        name: "undercounter fridge makeline with pickup",
        showTOAllProduct: false,
        image: "/images/products/undercounter-fridge-makeline-with-pickup.webp",
        category: "refrigerator",
    },
    {
        id: 87,
        name: "undercounter fridge",
        showTOAllProduct: false,
        image: "/images/products/undercounter-fridge.webp",
        category: "refrigerator",
    },
    {
        id: 88,
        name: "water cooler two tap",
        showTOAllProduct: true,
        image: "/images/products/water-cooler-two-tap.webp",
        category: "refrigerator",
    },
];
