interface card {
    id: number;
    name: string;
    commonName?: string;
    image: string;
    category: string;
}

export const cardData: card[] = [
    {
        id: 1,
        name: "1 2 2gn Pan Table Top Bain Marie",
        commonName: "",
        image: "/images/products/1_2_2gn_Pan_Table_Top_Bain_Marie.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 2,
        name: "Cash Counter 1",
        commonName: "",
        image: "/images/products/Cash_Counter_1.webp",
        category: "Counter Range",
    },
    {
        id: 3,
        name: "Cash Counter 2",
        commonName: "",
        image: "/images/products/Cash_Counter_2.webp",
        category: "Counter Range",
    },
    {
        id: 4,
        name: "casting Biryani Burner",
        commonName: "",
        image: "/images/products/casting_Biryani_Burner.webp",
        category: "burner",
    },
    {
        id: 5,
        name: "Catering Double Burner Table Top",
        commonName: "",
        image: "/images/products/Catering_Double_Burnner_Table_Top.webp",
        category: "burner",
    },
    {
        id: 6,
        name: "Customize Counter With Roof",
        commonName: "",
        image: "/images/products/Customize_Counter_With_Roof.webp",
        category: "Counter Range",
    },
    {
        id: 7,
        name: "Dhokla Cooker",
        commonName: "",
        image: "/images/products/Dhokla_Cooker.webp",
        category: "steamer range",
    },
    {
        id: 8,
        name: "Dhokla Steamer 6 Tray",
        commonName: "",
        image: "/images/products/Dhokla_Steamer_6_Tray.webp",
        category: "steamer range",
    },
    {
        id: 9,
        name: "Dhokla Steamer 8 Tray",
        commonName: "",
        image: "/images/products/Dhokla_Steamer_8_Tray.webp",
        category: "steamer range",
    },
    {
        id: 10,
        name: "Dish Landing",
        commonName: "",
        image: "/images/products/Dish_Landing.webp",
        category: "sink unit",
    },
    {
        id: 11,
        name: "Dish Landing With Table",
        commonName: "",
        image: "/images/products/Dish_Landing_With_Table.webp",
        category: "sink unit",
    },
    {
        id: 12,
        name: "Dosa Bhatti",
        commonName: "",
        image: "/images/products/Dosa_Bhatti.webp",
        category: "roti bhatti",
    },
    {
        id: 13,
        name: "Dosa Bhatti Table Top",
        commonName: "",
        image: "/images/products/Dosa_Bhatti_Table_Top.webp",
        category: "roti bhatti",
    },
    {
        id: 14,
        name: "Double burner",
        commonName: "",
        image: "/images/products/Double_burner.webp",
        category: "burner",
    },
    {
        id: 15,
        name: "Double Deck Stone Oven",
        commonName: "",
        image: "/images/products/Double_Deck_Stone_Oven.webp",
        category: "oven",
    },
    {
        id: 16,
        name: "Double Fryer 6 Litre",
        commonName: "",
        image: "/images/products/Double_Fryer_6_Litre.webp",
        category: "fryer range",
    },
    {
        id: 17,
        name: "Double Hydraulic Griller",
        commonName: "",
        image: "/images/products/Double_Hydraulic_Griller.webp",
        category: "griller range",
    },
    {
        id: 18,
        name: "Double Sink",
        commonName: "",
        image: "/images/products/Double_Sink.webp",
        category: "sink unit",
    },
    {
        id: 19,
        name: "Eight Pot Bain Maire",
        commonName: "",
        image: "/images/products/Eight_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 20,
        name: "Four Burner",
        commonName: "",
        image: "/images/products/Four_Burner.webp",
        category: "burner",
    },
    {
        id: 21,
        name: "Four Pot Bain Maire",
        commonName: "",
        image: "/images/products/Four_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 22,
        name: "Gn Pan Bain Marie 1",
        commonName: "",
        image: "/images/products/Gn_Pan_Bain_Marie_1.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 23,
        name: "Gn Pan Bain Marie 2",
        commonName: "",
        image: "/images/products/Gn_Pan_Bain_Marie_2.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 24,
        name: "Gn Pan Bain Marie 3",
        commonName: "",
        image: "/images/products/Gn_Pan_Bain_Marie_3.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 25,
        name: "Gn Pan Bain Marie 4",
        commonName: "",
        image: "/images/products/Gn_Pan_Bain_Marie_4.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 26,
        name: "Gn Pan Bain Marie 5",
        commonName: "",
        image: "/images/products/Gn_Pan_Bain_Marie_5.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 27,
        name: "Idli Cooker",
        commonName: "",
        image: "/images/products/Idli_Cooker.webp",
        category: "steamer range",
    },
    {
        id: 28,
        name: "Idli Steamer 6 Tray",
        commonName: "",
        image: "/images/products/Idli_Steamer_6_Tray.webp",
        category: "steamer range",
    },
    {
        id: 29,
        name: "Idli Steamer 8 Tray",
        commonName: "",
        image: "/images/products/Idli_Steamer_8_Tray.webp",
        category: "steamer range",
    },
    {
        id: 30,
        name: "Indian Pizza Oven",
        commonName: "",
        image: "/images/products/Indian_Pizza_Oven.webp",
        category: "oven",
    },
    {
        id: 31,
        name: "Indian Sandwich Griller",
        commonName: "",
        image: "/images/products/Indian_Sandwich_Griller.webp",
        category: "griller range",
    },
    {
        id: 32,
        name: "Khaman Steamer 6 Tray",
        commonName: "",
        image: "/images/products/Khaman_Steamer_6_Tray.webp",
        category: "steamer range",
    },
    {
        id: 33,
        name: "Khaman Steamer 8 Tray",
        commonName: "",
        image: "/images/products/Khaman_Steamer_8_Tray.webp",
        category: "steamer range",
    },
    {
        id: 34,
        name: "Masala Trolley",
        commonName: "",
        image: "/images/products/Masala_Trolley.webp",
        category: "Trolley",
    },
    {
        id: 35,
        name: "Ms Chinese Burner",
        commonName: "",
        image: "/images/products/Ms_Chinese_Burner.webp",
        category: "burner",
    },
    {
        id: 36,
        name: "Ms Rack 4 Shelves",
        commonName: "",
        image: "/images/products/Ms_Rack_4_Shelves.webp",
        category: "StorageRack",
    },
    {
        id: 37,
        name: "One Pot Bain Maire",
        commonName: "",
        image: "/images/products/One_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 38,
        name: "Pickup Table 1 Ohs And 2 Us",
        commonName: "",
        image: "/images/products/Pickup_Table_1_Ohs_And_2_Us.webp",
        category: "work table",
    },
    {
        id: 39,
        name: "Pickup Table 2 Ohs And 1 Us",
        commonName: "",
        image: "/images/products/Pickup_Table_2_Ohs_And_1_Us.webp",
        category: "work table",
    },
    {
        id: 40,
        name: "Pickup Table 2 Ohs And 2 Us",
        commonName: "",
        image: "/images/products/Pickup_Table_2_Ohs_And_2_Us.webp",
        category: "work table",
    },
    {
        id: 41,
        name: "Pot Burne",
        commonName: "",
        image: "/images/products/Pot_Burne.webp",
        category: "burner",
    },
    {
        id: 42,
        name: "Pot Sink",
        commonName: "",
        image: "/images/products/Pot_Sink.webp",
        category: "sink unit",
    },
    {
        id: 43,
        name: "Roti Bhatti Bullet",
        commonName: "",
        image: "/images/products/Roti_Bhatti_Bullet.webp",
        category: "roti bhatti",
    },
    {
        id: 44,
        name: "Roti Bhatti Bullet Table Top",
        commonName: "",
        image: "/images/products/Roti_Bhatti_Bullet_Table_Top.webp",
        category: "roti bhatti",
    },
    {
        id: 45,
        name: "Roti Bhatti Casting",
        commonName: "",
        image: "/images/products/Roti_Bhatti_Casting.webp",
        category: "roti bhatti",
    },
    {
        id: 46,
        name: "Roti Bhatti Casting Table Top",
        commonName: "",
        image: "/images/products/Roti_Bhatti_Casting_Table_Top.webp",
        category: "roti bhatti",
    },
    {
        id: 47,
        name: "Salamander",
        commonName: "",
        image: "/images/products/Salamander.webp",
        category: "oven",
    },
    {
        id: 48,
        name: "Service Table 1 Under Shelf",
        commonName: "",
        image: "/images/products/Service_Table_1_Under_Shelf.webp",
        category: "work table",
    },
    {
        id: 49,
        name: "Service Table 2 Under Shelf",
        commonName: "",
        image: "/images/products/Service_Table_2_Under_Shelf.webp",
        category: "work table",
    },
    {
        id: 50,
        name: "Service Table 2 Us With Backsplash",
        commonName: "",
        image: "/images/products/Service_Table_2_Us_With_Backsplash.webp",
        category: "work table",
    },
    {
        id: 51,
        name: "Service Table No Under Shelf",
        commonName: "",
        image: "/images/products/Service_Table_No_Under_Shelf.webp",
        category: "work table",
    },
    {
        id: 52,
        name: "Single Burner",
        commonName: "",
        image: "/images/products/Single_Burner.webp",
        category: "burner",
    },
    {
        id: 53,
        name: "Single Burner with table",
        commonName: "",
        image: "/images/products/Single_Burner_with_table.webp",
        category: "burner",
    },
    {
        id: 54,
        name: "Single deck Double tray Oven",
        commonName: "",
        image: "/images/products/Single_deck_Double_tray_Oven.webp",
        category: "oven",
    },
    // {
    //     id: 55,
    //     name: "single deck single tray oven",
    //      commonName: "",
    //     image: "/images/products/single_deck_single_tray_oven.webp",
    //     category:"oven",
    //
    // },
    {
        id: 56,
        name: "single Deck Stone Oven",
        commonName: "",
        image: "/images/products/single_Deck_Stone_Oven.webp",
        category: "oven",
    },
    {
        id: 57,
        name: "Single Fryer 4 Litre",
        commonName: "",
        image: "/images/products/Single_Fryer_4_Litre.webp",
        category: "fryer range",
    },
    {
        id: 58,
        name: "Single Fryer 6 Litre",
        commonName: "",
        image: "/images/products/Single_Fryer_6_Litre.webp",
        category: "fryer range",
    },
    {
        id: 59,
        name: "Single Hydraulic Griller",
        commonName: "",
        image: "/images/products/Single_Hydraulic_Griller.webp",
        category: "griller range",
    },
    {
        id: 60,
        name: "Single Sink",
        commonName: "",
        image: "/images/products/Single_Sink.webp",
        category: "sink unit",
    },
    {
        id: 61,
        name: "Single Sink With Table",
        commonName: "",
        image: "/images/products/Single_Sink_With_Table.webp",
        category: "sink unit",
    },
    {
        id: 62,
        name: "Six Pot 1 21gn Pan Bain Marie",
        commonName: "",
        image: "/images/products/Six_Pot_1_21gn_Pan_Bain_Marie.webp",
        category: "GN Pans Bain Marie",
    },
    {
        id: 63,
        name: "Six Pot Bain Maire",
        commonName: "",
        image: "/images/products/Six_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
    {
        id: 64,
        name: "Ss 4 Pot Dish Cooling Rack",
        commonName: "",
        image: "/images/products/Ss_4_Pot_Dish_Cooling_Rack.webp",
        category: "StorageRack",
    },
    {
        id: 65,
        name: "Ss Catering Burner",
        commonName: "",
        image: "/images/products/Ss_Catering_Burner.webp",
        category: "burner",
    },
    {
        id: 66,
        name: "Ss Counter",
        commonName: "",
        image: "/images/products/Ss_Counter.webp",
        category: "Counter Range",
    },
    {
        id: 67,
        name: "Ss Counter With Over 3 Side Covering",
        commonName: "",
        image: "/images/products/Ss_Counter_With_Over_3_Side_Covering.webp",
        category: "Counter Range",
    },
    {
        id: 68,
        name: "Ss Pickup Counter",
        commonName: "",
        image: "/images/products/Ss_Pickup_Counter.webp",
        category: "Counter Range",
    },
    {
        id: 69,
        name: "Ss Storage Rack",
        commonName: "",
        image: "/images/products/Ss_Storage_Rack.webp",
        category: "StorageRack",
    },
    {
        id: 70,
        name: "Stone Top Service Table",
        commonName: "",
        image: "/images/products/Stone_Top_Service_Table.webp",
        category: "work table",
    },
    {
        id: 71,
        name: "Three Burner",
        commonName: "",
        image: "/images/products/Three_Burner.webp",
        category: "burner",
    },
    {
        id: 72,
        name: "Three Sink",
        commonName: "",
        image: "/images/products/Three_Sink.webp",
        category: "sink unit",
    },
    {
        id: 73,
        name: "Three Tier Trolley",
        commonName: "",
        image: "/images/products/Three_Tier_Trolley.webp",
        category: "Trolley",
    },
    {
        id: 74,
        name: "Two Burner low Height",
        commonName: "",
        image: "/images/products/Two_Burner_low_Height.webp",
        category: "burner",
    },
    {
        id: 75,
        name: "Two Pot Bain Maire",
        commonName: "",
        image: "/images/products/Two_Pot_Bain_Maire.webp",
        category: "Bain Marie",
    },
];
